name: Generate Sitemap

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  generate-sitemap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Sitemap
        uses: cicirello/generate-sitemap@v1.10.2
        with:
          base-url-path: "https://conde86projects.github.io/curadente"

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add sitemap.xml
          git diff --quiet && git diff --staged --quiet || git commit -m "Update sitemap"
          git push 